---
#
# Provisions all the required dependencies for Wistar on the local host
#

- name: Provision Wistar
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install Junos-eznc dependancies
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
      - build-essential
      - libxml2-dev
      - libxslt1-dev
      - libz-dev
      - libffi-dev
      - libssl-dev
      - python-dev
      - git
      - python-pip

  - name: Install python-cryptography
    pip:
      name: cryptography
      editable: false

  - name: Install junos-eznc
    pip:
      name: junos-eznc
      editable: false

  - name: Install jxmlease
    pip:
      name: jxmlease
      editable: false

  - name: Install Wistar dependancies
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
      - qemu-kvm
      - libvirt-bin
      - socat
      - python-pexpect
      - python-libvirt
      - python-yaml
      - unzip
      - bridge-utils
      - python-numpy
      - genisoimage
      - python-netaddr
      - python-markupsafe
      - python-setuptools
      - mtools

  - name: Install Django
    pip:
      name: django
      version: 1.9.9
      editable: false

  - name: Install Python virtualBox
    pip:
      name: pyvbox
      editable: false

  - name: Create Wistar directory structure 1
    file:
      path: /opt/wistar
      state: directory
  - name: Create Wistar directory structure 2
    file:
      path: /opt/wistar/user_images
      state: directory
  - name: Create Wistar directory structure 3
    file:
      path: /opt/wistar/wistar-app
      state: directory
  - name: Create Wistar directory structure 4
    file:
      path: /opt/wistar/media
      state: directory
  - name: Create Wistar directory structure 5
    file:
      path: /opt/wistar/seeds
      state: directory
  - name: Create Wistar directory structure 6
    file:
      path: /opt/wistar/user_images/instances
      state: directory

  - name: Pull latest Wistar from Git
    git:
      repo: https://github.com/Juniper/wistar.git
      depth: 1
      dest: /opt/wistar/wistar-app/

  - name: Set up Wistar to run at boot (HACK)
    lineinfile:
      create: no
      dest: /etc/rc.local
      insertbefore: exit 0
      line: /opt/wistar/wistar-app/manage.py runserver 0.0.0.0:80 >>/var/log/wistar-stdout.log 2>&1 &

  - name: Create Wistar tables
    command: /opt/wistar/wistar-app/manage.py migrate
